# This workflow will do a clean installation of node dependencies, and then run the Specmatic tests.

name: Node.js CI for SPecmatic Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    # Install dependencies
    - name: Install Dependencies
      run: npm ci
    
    # Run the Specmatic Tests
    - name: Run Specmatic Tests
      run: npm run test:specmatic:generative
