# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI for SPecmatic Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    # Install dependencies
    - name: Install Dependencies
      run: npm ci
    
    # Start the server in the background
    - name: Start Server
      run: npm run start & 
            echo $! > server.pid # Save the server's process ID for cleanup later
    
    # Wait for the server to start
    - name: Wait for Server to be Ready
      run: npx wait-on http://localhost:3000
    
    # Run the Specmatic Tests
    - name: Run Specmatic Tests
      run: npm run specmatic:test
    
    # Stop the server
    - name: Stop Server
      run: |
            kill $(cat server.pid)
            rm server.pid
